#!/bin/sh

ssh ubuntu@3.90.34.145 <<EOF
    cd ~/node-jenkins-aws-ci-cd
    git pull origin master
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
    . ~/.nvm/nvm.sh
    nvm install v11.9.0
    npm install
    npm install -g nodemon pm2
    pm2 restart ecosystem.config.js
    exit
EOF
